//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : d.troickiy
//" Script Date        : Thu Mar  3 13:31:02 2022
//" Generated By       : LoadRunner Recorder (Build: 911)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	web.setUser('supervisor', lr.unmask('622098dfe11a170596776d13'), 'private.proverki.local:80');

	web.addAutoHeader('DNT', '1');

	web.addHeader('Upgrade-Insecure-Requests', '1');

//		"ParamName=KC_RESTART",
//		"RegExp=KC_RESTART=(.*?);",
//		SEARCH_FILTERS,
//		"Scope=Cookies",
//		"IgnoreRedirections=No",
//		LAST);
	

	web.url(
		{
			name : 'openPrivate', 
			url : '{privateURL}/', 
			resource : 0, 
			recContentType : 'text/html', 
			referer : '', 
			snapshot : 't228.inf', 
			mode : 'HTML', 
			extraRes :  [
				{url : '/private/static/js/2.6caa3188.chunk.js'},
				{url : '/private/static/js/main.b3e3c4c0.chunk.js', referer : ''},
				{url : '/private/static/media/loader.76756433.gif', referer : '{privateURL}/private/auth'},
				{url : '/private/static/media/FiraSans-Regular.34239e5e.woff2', referer : '{privateURL}/private/static/css/main.881e09d5.chunk.css'},
				{url : '/private/static/media/FiraSans-Light.4e01567d.woff2', referer : '{privateURL}/private/static/css/main.881e09d5.chunk.css'}
			]
		}
	);

	web.setSocketsOption('INITIAL_AUTH', 'BASIC');

	web.addHeader('Origin', '{privateURL}');

	web.regSaveParamRegexp({
	                       	paramName: 'SESSION_TOKEN', 
	                       	regExp: 'SESSION_TOKEN=(.*?)',
	                       	scope: 'Cookies',
	                       	IgnoreRedirections: 'No'
	                       });
	
	web.customRequest(
		{
			name : 'auth_2', 
			url : '{privateURL}/public/auth/authenticator/api/internalauth/auth?loaderKey=default', 
			method : 'POST', 
			resource : 0, 
			recContentType : 'application/json', 
			referer : '{privateURL}/private/auth', 
			snapshot : 't230.inf', 
			mode : 'HTML', 
			encType : ''
		}
	);

	web.url(
		{
			name : 'extendedprofile_2', 
			url : '{privateURL}/public/api/access-manager/api/users/current/extendedprofile', 
			resource : 0, 
			recContentType : 'application/json', 
			referer : '{privateURL}/private/auth', 
			snapshot : 't232.inf', 
			mode : 'HTML'
		}
	);

	return 0;
}

